admin:
  adminQQ:
  - 10086
broadcast:
  update: # 群号
    group:
    - 10086
    - 10086
system:
  name: RepiKo
  myQQ: 10086
  postURL: http://host:port/
  secret: post_secret
ygo:
  ygoPath: /path/to/ygoroot/
  servers:
    "233": ["s1.ygo233.com",233]
    编年史: ["duelstart.com",2333]
    2pick: ["2pick.mycard.moe",765]
