admin:
  adminQQ: # 管理者 QQ
  - 10086
  - 10086

broadcast: # broadcast 指令相关，可忽略
  update: 
    group: # 群号
    - 10086
    - 10086
  bot:
    private:
    - 10086
    - 10086
    - 10086

bot: # bot 相关
  name: RepiKo
  myQQ: 10086

connection:
  # 默认优先 ws，ws 无内容则使用 http 
  http:
    url: # http://host:port/   # HTTP 监听地址的 url（不是 post 的 url）
    secret: # post_secret      # post 密钥

  ws:
    url: # ws://host:port/     # 正向 WS 监听地址的 url

font: # 字体相关
  normal: # font/file.ttf
  AA: # font/file.ttf
  tex: # font/file.ttf

ygo: # ygo 相关指令的相关设置
  ygoPath: # /path/to/ygoroot/ # ygopro 路径
  servers: # 服务器列表
    "233": ["s1.ygo233.com",233]
    编年史: ["duelstart.com",2333]
    2pick: ["2pick.mycard.moe",765]

deepl:
  key: # my_auth_key
